-- AUTO-GENERATED by scripts/build-hammerspoon-theme.mjs
-- Source of truth: src/themes/_active.ts  →  src/themes/<active>.ts
-- DO NOT EDIT — your changes will be overwritten on the next `npm run build`.

return {
  accents = {
    status = {
      border = { red = 0.6902, green = 0.7451, blue = 0.7725, alpha = 0.45 },
      text = { red = 0.9451, green = 0.9451, blue = 0.9529, alpha = 1 },
      h1 = { red = 0.8118, green = 0.8471, blue = 0.8627, alpha = 1 },
      h2Muted = { red = 0.9451, green = 0.9451, blue = 0.9529, alpha = 0.78 },
      smallMuted = { red = 0.9451, green = 0.9451, blue = 0.9529, alpha = 0.82 },
    },
    weather = {
      border = { red = 0.7843, green = 0.7216, blue = 0.6431, alpha = 0.45 },
      text = { red = 0.9451, green = 0.9451, blue = 0.9529, alpha = 1 },
      h1 = { red = 0.9098, green = 0.8784, blue = 0.8314, alpha = 1 },
      h2Muted = { red = 0.9451, green = 0.9451, blue = 0.9529, alpha = 0.78 },
      smallMuted = { red = 0.9451, green = 0.9451, blue = 0.9529, alpha = 0.82 },
    },
    calendar = {
      border = { red = 0.7843, green = 0.7843, blue = 0.7843, alpha = 0.45 },
      text = { red = 0.9451, green = 0.9451, blue = 0.9529, alpha = 1 },
      h1 = { red = 0.8667, green = 0.8667, blue = 0.8667, alpha = 1 },
      h2Muted = { red = 0.9451, green = 0.9451, blue = 0.9529, alpha = 0.76 },
      smallMuted = { red = 0.9451, green = 0.9451, blue = 0.9529, alpha = 0.82 },
    },
    nowplaying = {
      border = { red = 0.7059, green = 0.6667, blue = 0.7451, alpha = 0.45 },
      text = { red = 0.9451, green = 0.9451, blue = 0.9529, alpha = 1 },
      h1 = { red = 0.8471, green = 0.8314, blue = 0.8627, alpha = 1 },
      h2Muted = { red = 0.9451, green = 0.9451, blue = 0.9529, alpha = 0.76 },
      smallMuted = { red = 0.9451, green = 0.9451, blue = 0.9529, alpha = 0.82 },
    },
  },

  status = {
    good = { red = 0.6549, green = 0.9529, blue = 0.8157, alpha = 1 },
    warn = { red = 0.9922, green = 0.902, blue = 0.5412, alpha = 1 },
    bad = { red = 0.9961, green = 0.7922, blue = 0.7922, alpha = 1 },
  },

  layout = {
    width = 210,
    radius = 8,
    borderWidth = 1,
    cardBg = { red = 0.0392, green = 0.0471, blue = 0.0627, alpha = 0.62 },
    fontFamily = "\"SF Mono\"",
  },
}
