-- AUTO-GENERATED by scripts/build-hammerspoon-theme.mjs
-- Source of truth: src/themes/_active.ts  →  src/themes/<active>.ts
-- DO NOT EDIT — your changes will be overwritten on the next `npm run build`.

return {
  accents = {
    status = {
      border = { red = 0.5686, green = 0.8431, blue = 0.8902, alpha = 0.7 },
      text = { red = 0.7922, green = 0.8275, blue = 0.9608, alpha = 1 },
      h1 = { red = 0.5686, green = 0.8431, blue = 0.8902, alpha = 1 },
      h2Muted = { red = 0.7216, green = 0.7529, blue = 0.8784, alpha = 0.82 },
      smallMuted = { red = 0.6471, green = 0.6784, blue = 0.7961, alpha = 0.78 },
    },
    weather = {
      border = { red = 0.9608, green = 0.6627, blue = 0.498, alpha = 0.6 },
      text = { red = 0.7922, green = 0.8275, blue = 0.9608, alpha = 1 },
      h1 = { red = 0.9608, green = 0.6627, blue = 0.498, alpha = 1 },
      h2Muted = { red = 0.7216, green = 0.7529, blue = 0.8784, alpha = 0.82 },
      smallMuted = { red = 0.6471, green = 0.6784, blue = 0.7961, alpha = 0.78 },
    },
    calendar = {
      border = { red = 0.651, green = 0.8549, blue = 0.5843, alpha = 0.6 },
      text = { red = 0.7922, green = 0.8275, blue = 0.9608, alpha = 1 },
      h1 = { red = 0.651, green = 0.8549, blue = 0.5843, alpha = 1 },
      h2Muted = { red = 0.7216, green = 0.7529, blue = 0.8784, alpha = 0.82 },
      smallMuted = { red = 0.6471, green = 0.6784, blue = 0.7961, alpha = 0.78 },
    },
    nowplaying = {
      border = { red = 0.7765, green = 0.6275, blue = 0.9647, alpha = 0.6 },
      text = { red = 0.7922, green = 0.8275, blue = 0.9608, alpha = 1 },
      h1 = { red = 0.7765, green = 0.6275, blue = 0.9647, alpha = 1 },
      h2Muted = { red = 0.7216, green = 0.7529, blue = 0.8784, alpha = 0.82 },
      smallMuted = { red = 0.6471, green = 0.6784, blue = 0.7961, alpha = 0.78 },
    },
    keepawake = {
      border = { red = 0.651, green = 0.8549, blue = 0.5843, alpha = 0.6 },
      text = { red = 0.7922, green = 0.8275, blue = 0.9608, alpha = 1 },
      h1 = { red = 0.651, green = 0.8549, blue = 0.5843, alpha = 1 },
      h2Muted = { red = 0.7216, green = 0.7529, blue = 0.8784, alpha = 0.82 },
      smallMuted = { red = 0.6471, green = 0.6784, blue = 0.7961, alpha = 0.78 },
    },
  },

  status = {
    good = { red = 0.651, green = 0.8549, blue = 0.5843, alpha = 1 },
    warn = { red = 0.9333, green = 0.8314, blue = 0.6235, alpha = 1 },
    bad = { red = 0.9294, green = 0.5294, blue = 0.5882, alpha = 1 },
  },

  layout = {
    width = 220,
    radius = 14,
    borderWidth = 2,
    cardBg = { red = 0.1412, green = 0.1529, blue = 0.2275, alpha = 0.92 },
    fontFamily = "Inter",
  },
}
